name: Lua Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt-check:
    name: Check Lua Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stylua
        run: |
          curl -L -o stylua.zip "https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip"
          unzip stylua.zip -d /usr/local/bin
          chmod +x /usr/local/bin/stylua

      - name: Check Lua formatting
        run: |
          stylua --check .
